added ImageMagick / ufraw to compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -11,3 +11,50 @@ if pack = LanguagePack.detect(ARGV[0], ARGV[1])
     pack.compile
   end
 end
+
+system %Q{
+# Fail fast and fail hard.
+set -eo pipefail
+
+# Prepend proper path for virtualenv hackery. This will be deprecated soon.
+export PATH=:/usr/local/bin:$PATH
+
+# Paths.
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
+ROOT_DIR=$(dirname $BIN_DIR)
+BUILD_DIR=$1
+CACHE_DIR=$2
+
+# We'll need to send these statics to other scripts we `source`.
+# export PIP_DOWNLOAD_CACHE
+export BUILD_DIR
+
+# Syntax sugar.
+
+function puts-step (){
+  echo "-----> $@"
+}
+
+# ## Build Time
+#
+
+# Switch to the repo's context.
+cd $BUILD_DIR
+
+IM_LOCATION="im"
+
+mkdir -p $IM_LOCATION
+
+# Install ImageMagick
+IM_VERSION="6.7.8-8"
+IM_URL="https://download-pixelapse.s3.amazonaws.com/im-$IM_VERSION.tar.gz"
+puts-step "Bundling ImageMagick version $IM_VERSION"
+curl --silent --max-time 60 --location "$IM_URL" | tar xz
+
+# ufraw dependency
+UFRAW_VERSION="0.18"
+UFRAW_URL="https://download-pixelapse.s3.amazonaws.com/ufraw-bin-$UFRAW_VERSION.tar.gz"
+puts-step "Bundling ufraw version $UFRAW_VERSION"
+curl --silent --max-time 60 --location "$UFRAW_URL" | tar xz -C $IM_LOCATION
+  
+}
